name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: g++ -std=c++11 -o bytecode_adder bytecode_adder.cpp
    - name: Test
      run: ./bytecode_adder
